services:
  # Laravel App
  quinbot-app:
    build: ./app
    container_name: quinbot_php
    volumes:
      - ./app:/var/www
      - ./shared_storage:/var/www/storage/app/public # Dùng chung folder để lưu video

  # Python Engine (Worker)
  quinbot-engine:
    build: ./engine
    container_name: quinbot_python
    volumes:
      - ./engine:/app
      - ./shared_storage:/app/media # Python ghi video vào đây
    command: celery -A main worker --loglevel=info -P solo
    depends_on:
      - redis

  redis:
    image: redis:alpine